# NOTE: specify zsh at 'tss' alias or function
#       because such as multi-agent-shogun needs bash
if-shell '[ -x /usr/bin/zsh ]' {
  set -g default-shell /usr/bin/zsh
} {
  set -g default-shell /bin/bash
}

source-file ~/dotfiles/tmux/home.tmux.conf
